name: Run tests and build image

on:
  push:
    branches:
    - main

jobs:
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Pytest
      run: pytest

  e2e_tests:
    name: Run end-to-end tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        start: streamlit run model_dashboard.py --server.headless=true
